### ISSUE TITLE
Drag and drop images doesn't work on Mac

### ISSUE THREAD

**Issue by zjenkin13** [dimdenGD/OldTweetDeck#216]
When i go to drag and drop images on my new Mac, after a minute or so of loading the page they all start to open in a new tab and i have to manually select the ones i want to use. Not having this issue on my PC, or other web pages, or even my old Mac it was never an issue. Confirmed with one of my friends and he is having the exact same problem.

**Comment by i13302** [comment]
Probably this bug was fixed by this commit https://github.com/dimdenGD/OldTweetDeck/commit/8278f3a48dacffecc4c947445561ea4fd3411074 .

Try latest version.
https://github.com/dimdenGD/OldTweetDeck/releases

I can upload image using drag and drop on macOS 13.6.4 and latest OldTweetDeck v3.5.3.

**Comment by zjenkin13** [comment]
Still doesn't work for me. It only works initially for the first few mins then pics start opening in a new tab. I'm on the latest macOS Sanoma 14.3 and latest OldTweetDeck v3.5.4.
