### ISSUE TITLE
User coeloms not working  

### ISSUE THREAD

**Issue by ItsBluey** [dimdenGD/OldTweetDeck#30]
infinite loading 
![image](https://github.com/dimdenGD/OldTweetDeck/assets/20117258/ecb62715-8c4e-4b81-b5f1-661d6d5ee661)

**Comment by dohq** [comment]
This is a Twitter issue, not OldTweetDeck.

**Comment by SilentPrayeCG** [comment]
Same with me. But that was in regular legacy tweetdeck as well, while it still worked. It fixed by itself after some time.

**Comment by forestpassineau** [comment]
Having this issue this morning... Was working perfectly up till now.  Tried updating to 2.0.5 and issue still exists.  Up till now all columns loaded without issue but this morning many of my normal user profile colums no longer load and just continue to spin saying loading but nothing happens.

**Comment by dimdenGD** [comment]
Duplicate of https://github.com/dimdenGD/OldTweetDeck/issues/34

**Comment by dimdenGD** [comment]
Released new version, update!
