### ISSUE TITLE
4.1.0 even enabling rate limit override briefly does nothing

### ISSUE THREAD

**Issue by snowbound** [dimdenGD/OldTweetDeck#409]
In Brave I frequently get rate limited so that in OldTweetdeck I only see Home and Notification columns. In the past if I briefly enabled Rate Limiting Override the other columns would populate. In 4,1.0 doing that does nothing to populate the other columns including User column for my main account.

**Comment by dimdenGD** [comment]
fixed

**Comment by snowbound** [comment]
Is there anything else I should do other than download and installing this extension via Unpacked? Asking because even after reloading the tab with Rate Limiting Override enabled still having the same issue? Has X rate limited me entirely for 24 hours?
