### ISSUE TITLE
Page not loading/stuck on "something went wrong" screen

### ISSUE THREAD

**Issue by Classsic36** [dimdenGD/OldTweetDeck#452]
Completely unable to load OTD as of Nov 1st. Worked for a few hours on Nov 2nd, but hasn't worked since.

Have tried reinstalling OTD, BTD and Chrome, tried multiple accounts and tried both Windows 11 & macOS 26.0.1 and 26.1.

Chrome version 142.0.7444.60 & OldTweetDeck v4.3.2 with BetterTweetDeck v4.11.3

![image](https://i.postimg.cc/3xc4xy1X/SCR-20251104-tqbq.jpg)

Console errors:
![image](https://i.postimg.cc/N0CWVtgB/SCR-20251104-tucb.png)

![image](https://i.postimg.cc/yNpw5KVV/SCR-20251104-tugm.png)

**Comment by flawzyyy** [comment]
Having same issue now, just started today

**Comment by AT-4** [comment]
Also encountering the same issue

**Comment by silveratelier** [comment]
Yep, me too. I have updated both oldtweetdeck and oldtwitter to the newest version for chrome and also firefox and have the issue in both.

**Comment by dimdenGD** [comment]
Weirdly it seems to work fine for me 🤔

**Comment by dimdenGD** [comment]
Does this still happen when you disable BetterTD?

**Comment by Classsic36** [comment]
> Does this still happen when you disable BetterTD?

Yes

The last error that was spammed 500+ times in the previous console log doesn't appear though

<img width="612" height="904" alt="Image" src="https://github.com/user-attachments/assets/681daeeb-307e-435c-a16c-0efb5f2ffb49" />

**Comment by silveratelier** [comment]
> Yep, me too. I have updated both oldtweetdeck and oldtwitter to the newest version for chrome and also firefox and have the issue in both.

Also, logging in just gives me a white screen now.

<img width="1260" height="774" alt="Image" src="https://github.com/user-attachments/assets/19d1ae76-ee2a-4ab3-a422-33c7c2bdea88" />

**Comment by dimdenGD** [comment]
I think its most likely caused by this error:
<img width="645" height="192" alt="Image" src="https://github.com/user-attachments/assets/bba8e955-5aea-46de-8939-e56cdce447f1" />
Can you go to Network tab and check why requests failed (especially `ondemand.s`)

**Comment by Classsic36** [comment]
> I think its most likely caused by this error: Can you go to Network tab and check why requests failed (especially `ondemand.s`)

ondemand.s returns code 200

<img width="772" height="134" alt="Image" src="https://github.com/user-attachments/assets/477bd3be-56ff-42cf-9c89-d64eea795182" />

<img width="410" height="831" alt="Image" src="https://github.com/user-attachments/assets/b61fe370-d43f-4020-a4c4-d0f26787dbf4" />

**Comment by dimdenGD** [comment]
Can you go to `verify_credentials.json` request and scroll to request headers and send screenshot of it (blur `Cookie` part though)

**Comment by Classsic36** [comment]
> Can you go to `verify_credentials.json` request and scroll to request headers and send screenshot of it (blur `Cookie` part though)

<img width="1528" height="830" alt="Image" src="https://github.com/user-attachments/assets/ce45bff1-133d-4428-bab1-2a1503936aa7" />

**Comment by djarnoldmx** [comment]
<img width="596" height="227" alt="Image" src="https://github.com/user-attachments/assets/76c9928c-c613-4b00-a6ac-bf026de29628" />

**Comment by djarnoldmx** [comment]
Now work again after logout and login again

**Comment by Classsic36** [comment]
> Now work again after logout and login again

Lucky! Tried multiple times, not working here :(

**Comment by KingVulcam** [comment]
For me, even unlogging/logging still shows this error

**Comment by dimdenGD** [comment]
For some reason half of people have this endpoint working and other half doesnt which causes it to break... Thanks melon musk

**Comment by porygon3000** [comment]
Same here, sometimes work after refreshing like a million times

**Comment by dimdenGD** [comment]
Fixed in latest version

**Comment by Classsic36** [comment]
> Fixed in latest version

Thank you so much!

**Comment by roserade-d** [comment]
Hi sorry to bother, but this still doesn't seem to be working for me. 

<img width="930" height="933" alt="Image" src="https://github.com/user-attachments/assets/84651527-8b47-423d-9fab-077224659070" />
